name: shoobx.rml2odt

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  workflow_dispatch:

jobs:
  test:
    # nail ubuntu version here, fonts can change that will affect ODT rendering,
    # causing image mismatches
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:

    - name: Check out source
      uses: actions/checkout@v3

    - name: Install Libreoffice and ghostscript
      run: |
        sudo apt-get update
        sudo apt-get install --yes libreoffice
        sudo apt-get install --yes ghostscript

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      if: matrix.python-version == 3.11
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
